language: r

warnings_as_errors: true

apt_packages:
  - ghostscript

r_binary_packages:
  - XML
  - png
  - jpeg
  - base64enc
  - testthat

r_packages:
  - gridSVG
  - grImport
  - lattice
  - cluster
  - colorspace
  - survival

r_github_packages:
  - sjp/grConvert

notifications:
  email:
    on_success: change
    on_failure: change
